### ISSUE TITLE
Previous Used is always blank

### ISSUE THREAD

**Issue by DavidFW1960** [custom-components/authenticated#45]
**Version of the custom_component**

1.0.6
Sorry I keep breaking this @ludeeus 
**Describe the bug**
All my IP addresses show no previously used time/date in yaml or in the sensor
**log**

```
No log to add. Not generating any error just not showing a last used.
2001:4860:4801:8053::13:
  city: Ashburn
  country: United States
  hostname: rate-limited-proxy-2001-4860-4801-8053-0000-0000-0000-0013.google.com
  last_used_at: '2019-07-12T01:05:04.753358+00:00'
  prev_used_at: null
  region: Virginia
  user_id: bxxxxxxxxxxxxxxxxxxxxxxxxxx

172.30.32.2:
  city: null
  country: null
  hostname: hassio_supervisor.hassio
  last_used_at: '2019-07-09T18:32:08.615605+00:00'
  prev_used_at: null
  region: null
  user_id: 5xxxxxxxxxxxxxxxxxxxxxxx
```
