### ISSUE TITLE
exclude RANGE of IPs (not LIST of IPs)

### ISSUE THREAD

**Issue by enrysan0** [custom-components/authenticated#55]
Hi,

it seems I didn't explain well my problem with the precend issue that was closed without a truly sensate answer to my question. 
So here I'm to explain again with other words my issue. If it's not an issue, but a feature not implemented yet, sorry if I posted in the wrong section and please move this topic to the feature request. Thanks

**Version of the custom_component**
1.2.2

**Describe the bug**
is this component able to exclude **RANGE** of IPs and not only LIST of IPs? 

I know that with this configuration I can exclude a LIST o IPs:
```
- platform: authenticated
  enable_notification: yes
  exclude:
      - 108.177.64.1
      - 108.177.70.1
      - 108.177.71.1
```

But I'm triyng to exclude a **RANGE** of IPs: for example all the IPs from 108.177.64.1 to 108.177.64.254. Can I simple use a configuration like this:
```
- platform: authenticated
  enable_notification: yes
  exclude:
      - 108.177.64.0
```
or
```
- platform: authenticated
  enable_notification: yes
  exclude:
      - 108.177.64.0/24
```

or simple this component isn't able to exclude RANGE of IPs?

Thanks for your time.
