### ISSUE TITLE
Exclude from api but include in the sensor

### ISSUE THREAD

**Issue by Salvora** [custom-components/authenticated#74]
**Is your feature request related to a problem? Please describe.**
I want to see who logged in from my local network but I want to exclude these from the api calls.

**Describe the solution you'd like**
Add a seperate exclude option to api part like this
```yaml
  api:
    provider: 'ipapi'
    exclude:
      - "local ip"
      - "other ip"
```
I am not sure how this works but it will be helpful to reduce unnecessary api calls.
